- hosts: pg-img
  become: yes

  tasks:
    - name: Add Patroni python dependencies
      apt:
        state: present
        name: "{{ item }}"
      with_items:
        - python3-pip
        - python3-psycopg2

    - name: Install Patroni
      pip:
        name: patroni[etcd]==2.0.1

    - name: Add Patroni systemd unit file
      template:
        src: template/patroni.service.j2
        dest: /etc/systemd/system/patroni.service

    - name: Add Patroni config directory
      file:
        state: directory
        path: /etc/patroni
        owner: postgres
        group: postgres

    - name: Add Patroni config file
      template:
        src: template/patroni.yml.j2
        dest: /etc/patroni/patroni.yml.tmpl
        owner: postgres
        group: postgres
